config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'rooms/index'
  get 'home/index', as: 'home'
  root 'home#index'
  resources :rooms
  resources :users
  resources :rooms do
    resources :messages
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #problema al cerrar la sesion con devise 
  devise_scope :user do 
    get 'users/sign_out' => "devise/sessions#destroy"
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
  before_create :confirm_participant
  def confirm_participant
    if self.room.is_private
      is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
      throw :abort unless is_participant
    end
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  has_many :messages
  has_many :participants, dependent: :destroy
  after_create_commit { broadcast_if_public }
  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end
  
  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id )
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create(content: msg_params[:content], room_id: params[:room_id])
  end

  private

  def msg_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
  end
  def create
    @room = Room.create(name: params["room"]["name"])
  end
  def show
    @single_room = Room.find(params[:id])
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
    @room = Room.new
    @message = Message.new
    @messages = @single_room.messages
    render "index"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    @room_name = get_name(@user, @current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, @current_user], @room_name)
    @messages = @single_room.messages

    render "rooms/index"
  end

  private
  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <%= render partial: 'layouts/navbar' %>
    <section class="section">
      <section class="section">
        <div class="container is-flex flex-direction-columns">
          <div class="columns is-vcentered">
            <div class="column is-4 mx-6">
              <h1 class="title has-text-light">Bienvenido a ILine</h1>
              <h2 class="subtitle has-text-light">Comunicate facilmente y con Confianza </h2>
              <p class="has-text-justified	">Nuestra aplicación de chat te permite conectarte con amigos, familiares y colegas en tiempo real. Chatea, comparte archivos y mantén conversaciones grupales con facilidad</p>
              <!--parte de los botones-->
              <div class="section">
                <% if user_signed_in? %>
                  <div class="buttons">
                    <%= link_to 'sing out', destroy_user_session_path, method: :delete, class: "button is-link is-responsive"%>
                  </div>
                <% else %>
                  <div class="buttons">
                    <%= link_to 'sing in', new_user_session_path, class: "button is-link is-responsive" %>
                    <%= link_to 'sing up', new_user_registration_path, class: "button is-link is-responsive" %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="column is-6 mx-6">
              <figure class="image">
                <img class="" src="https://res.cloudinary.com/dyq41tgzg/image/upload/v1718898313/familychat/familychat_home_ntkuw7.jpg" alt="familychat_home image" style="border-radius: 10%;">
              </figure>
            </div>
          </div>
        </div>



      </section>


    </section>
  </body>
</html>

app/views/layouts/_navbar.html.erb
<nav class="navbar has-shadow is-link">
  <!--logo de la nav-->
  <div class="navbar-brand">
    <a class="navbar-item" href="<%= home_path %>">
      <img src="https://res.cloudinary.com/dyq41tgzg/image/upload/v1719613604/ILINE/logo2-removebg-preview_e3viyl.png" alt="familychat logo", style="max-height: 7rem;">
    </a>
    <a class="navbar-burger" id="burger">
      <span></span>
      <span></span>
      <span></span>
    </a>
  </div>
  <!-- menu de la navbar-->
  <div class="navbar-menu" id="nav-links">
    <div class="navbar-start">
      <% if user_signed_in? %>
        <%= link_to 'Salas', rooms_path, class: "navbar-item" %>
        <%= link_to 'Mi Perfil', edit_user_registration_path, class: "navbar-item" %>
      <% end %>
    </div>
  </div>
</nav>

<script>
  const burgerIcon = document.querySelector('#burger');
  const burgerMenu = document.querySelector('#nav-links');

  burgerIcon.addEventListener('click', () => {
    burgerMenu.classList.toggle('is-active');
  });
</script>

app/views/layouts/_new_message_form.html.erb
<!--<div class="form-group msg-form">
  <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>-->

<div class=" has-background-link py-6 px-6 is-flex-direction-column" style="width: 80%; position: fixed; bottom: 0;" >
  <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex" ) do |f| %>
    <div class="field is-grouped">
      <p class="control is-expanded">
        <%= f.text_field :content, id: 'chat-text', class: "input", autocomplete: 'off', placeholder: "mensaje"%>
      </p>
      <p class="control">
        <%= f.submit data: { disable_with: false }, class: "button is-light is-responsive" %>
      </p>            
    </div>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<!--<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
  <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>-->

<div class="px-1">
  <%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
    <div class="field is-grouped">
      <p class="control is-expanded">
        <%= f.text_field :name, class: "input", autocomplete: 'off', placeholder: "nombre"%>
      </p>
      <p class="control">
        <%= f.submit data: { disable_with: false }, class: "button is-link is-responsive" %>
      </p>            
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="box has-background-link mx-6" style="max-width: 15rem;">
  <h6 class="has-text-black is-size-5"> <%= message.user.email%> </h6>
  <p><%= message.content %></p>
</div>
<!--
  <div class="box has-background-light mx-6 is-pulled-right" style="max-width: 15rem;">
    <h6 class="has-text-black is-size-5"> <%= message.user.email%> </h6>
    <p><%= message.content %></p>
</div>
-->

app/views/rooms/_room.html.erb
<div> <%= link_to room.name, room %> </div>

app/views/rooms/index.html.erb
<!DOCTYPE html>   
<html>   
  <body> 
    <%= render partial: 'layouts/navbar' %>
      
    <div class="columns is-gapless">
      
      <div class="column has-background-white" style="height: 58.4rem;">
        
        <!-- <div>
          <%= turbo_stream_from "users" %>
          <div id="users">
            <%= render @users %>
          </div>
        </div> -->
        <div>
          <%= turbo_stream_from "users" %>
          <div class="section" id="users">
            <h4 class="title has-text-centered mt-2 has-text-black"> Users </h4>
            <% @users.each do |user| %>
              <div class="is-flex-direction-column has-background-link my-2 px-3 py-3" style="border-radius: 0%;">
                <%= link_to user.email, user, class: "has-text-light" %>
              </div>
            <% end %>
          </div>
        </div>
        
        
        <!-- <div>
          <%= turbo_stream_from "rooms" %>
          <div id="rooms">
            <%= render @rooms %>
          </div>
        </div> -->
        <h4 class="title has-text-centered has-text-black"> Crea un Grupo </h4>
        <%= render partial: "layouts/new_room_form" %>
        <div>
          <%= turbo_stream_from "rooms" %>
          <div class="section" id="rooms">
            <h4 class="title has-text-centered mt-2 has-text-black"> Grupos </h4>
            <% @rooms.each do |room| %>
              <div class="is-flex-direction-column my-2 has-text-centered" style="border-radius: 0%;">
                <%= link_to room.name, room, class: "button is-link has-text-light", style: "min-width: 17rem;" %>
              </div>
            <% end %>
          </div>
        </div>

      </div>

      <div class="column is-four-fifths">
        <% if @single_room %>
          <h4 class="title has-text-centered mt-6"> <%= @user&.email || @single_room.name %> </h4>
          <%= turbo_stream_from @single_room %>
          <div id="messages">
            <%= render @messages %>
          </div>
          <%= render partial: 'layouts/new_message_form' %>
        <% end %>
      </div>
    </div>

  </body>
</html>

app/views/users/_user.html.erb
<div class="user user-<%= user.id %>">
  <h3 class="title is-4">
    <%= link_to user.email, user %>
  </h3>
</div>